<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260108212513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reset_password_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_16646B41A76ED395 ON reset_password_requests (user_id)');
        $this->addSql('ALTER TABLE reset_password_requests ADD CONSTRAINT FK_16646B41A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_tags DROP CONSTRAINT fk_251a5b089eea759');
        $this->addSql('ALTER TABLE inventory_tags DROP CONSTRAINT fk_251a5b08bad26311');
        $this->addSql('DROP TABLE inventory_tags');
        $this->addSql('ALTER TABLE inventories DROP custom_id_format');
        $this->addSql('ALTER TABLE inventories DROP custom_fields_config');
        $this->addSql('ALTER TABLE inventories DROP view_count');
        $this->addSql('ALTER TABLE inventories ALTER is_public SET DEFAULT false');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inventory_tags (inventory_id UUID NOT NULL, tag_id UUID NOT NULL, PRIMARY KEY (inventory_id, tag_id))');
        $this->addSql('CREATE INDEX idx_251a5b089eea759 ON inventory_tags (inventory_id)');
        $this->addSql('CREATE INDEX idx_251a5b08bad26311 ON inventory_tags (tag_id)');
        $this->addSql('ALTER TABLE inventory_tags ADD CONSTRAINT fk_251a5b089eea759 FOREIGN KEY (inventory_id) REFERENCES inventories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inventory_tags ADD CONSTRAINT fk_251a5b08bad26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_requests DROP CONSTRAINT FK_16646B41A76ED395');
        $this->addSql('DROP TABLE reset_password_requests');
        $this->addSql('ALTER TABLE inventories ADD custom_id_format JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE inventories ADD custom_fields_config JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE inventories ADD view_count INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE inventories ALTER is_public SET DEFAULT true');
    }
}
